FROM tensorflow/tensorflow:2.8.0-gpu

SHELL ["/bin/bash", "-c"]

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
RUN apt-get update
RUN apt install -y protobuf-compiler
RUN apt install -y git-all
RUN apt install -y jq

WORKDIR /opt/ml/code

COPY src src
COPY requirements.txt .
COPY *.yaml .
COPY scripts/sagemaker-train-swav.sh train
RUN chmod +x train
ENV PATH="/opt/ml/code:$PATH"

RUN python -m pip install -r requirements.txt

RUN git clone https://github.com/tensorflow/models.git
WORKDIR models/research
RUN protoc object_detection/protos/*.proto --python_out=.
RUN cp object_detection/packages/tf2/setup.py .
RUN python -m pip install --use-feature=2020-resolver .

WORKDIR ..
RUN apt-get install wget
RUN wget https://download.tensorflow.org/models/object_detection/tf2/20200711/centernet_resnet50_v1_fpn_512x512_coco17_tpu-8.tar.gz --no-check-certificate
RUN tar -xvzf centernet_resnet50_v1_fpn_512x512_coco17_tpu-8.tar.gz

WORKDIR ..
RUN mkdir logs
RUN mkdir ckpt
RUN mkdir tensorboard_logs
